on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator, OS:15.2, name:iPhone 13']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        env:
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -project PetProject.xcodeproj -scheme 'PetProject' -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO