on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 13']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'

      - name: Secrets
        run: |
          echo "${{ secrets.SOMESECRET }}"

      - name: Build
        env:
          destination: ${{ matrix.destination }}
        run: |
          xcodebuild clean build -project PetProject.xcodeproj -scheme "PetProject" -destination "platform=iOS Simulator,OS=15.2,name=iPhone 13" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO